### ISSUE TITLE
M17 DV mode addition

### ISSUE THREAD

**Issue by sp5wwp** [pupeno/repeater_world#509]
The list of modes lacks [M17](https://m17project.org) button.

**Comment by pupeno** [comment]
This is really cool. I'll add this mode ASAP. Can you help me understand if there are values associated with this mode? For example, FM has a CTCSS code, D-Star has a port, DMR has color codes, etc. When a repeater is an M17 repeater, what values should be tracked and provided for importing to radios?

**Comment by pupeno** [comment]
This is now done and live.

**Comment by sp5wwp** [comment]
Thank you! We now need to fill the list with repeaters :)

Repeaterbook has [37 entries](https://www.repeaterbook.com/M17).

**Comment by pupeno** [comment]
Yeah. Getting the data in is half the problem. I am importing data from various places but not Repeater Book. I don't believe they would be happy with that, so the data would have to be imported from somewhere else or be recreated manually. Good thing is that after that the data in Repeater World is free, exportable, reusable.

**Comment by pupeno** [comment]
You can now go ahead and add repeaters directly: https://www.youtube.com/watch?v=d836bhH156o
